### ISSUE TITLE
Plot are lagging 4 days

### ISSUE THREAD

**Issue by berketurker14** [emirhanai/Cryptocurrency-Prediction-with-Artificial-Intelligence#2]
Prediction
![image](https://user-images.githubusercontent.com/45368526/193457605-e415c021-efca-4332-98f3-0cf1ea80eb3a.png)
Start Of My dataset(2500 lines total)
![image](https://user-images.githubusercontent.com/45368526/193457631-43817ce4-a051-401f-a02d-8d9c1656ed95.png)

I'd like to make predictions for dates after 10-2-2022(Last day of my dataset)
And also plot test data is dependent to dataset, dk if that is an issue

**Comment by emirhanai** [comment]
You can input data of 10-02-2022 (high,low,average price etc..). After than software will work.
Thanks..

example = model.predict([10-02-2022_low,10-02-2022_high...])
print(example)
